Adding Kubectl to Docker container
rancher/cli pull request #277
Opened 2020-05-15 02:00 UTC by Arno500

This would actually be nice to be able to use Rancher CLI with kubectl commands in CI/CD pipelines and only provide a token. It's also not much to add to the container.

2021-07-21 14:27 UTC, gaby commented
Any plans to merge this?

2022-05-23 11:44 UTC, Trackhe approved these changes

2022-05-23 11:46 UTC, Trackhe commented
Please merge this.

2022-05-23 14:39 UTC, Arno500 commented
I updated the commit to the latest Alpine as in the main branch

2022-05-24 12:05 UTC, gaby commented
@Arno500 alpine comes with wget, that way you dont have to install curl.

2022-05-24 13:00 UTC, Trackhe commented
@Arno500 you can take this.
```
FROM alpine:3.13
RUN apk add --no-cache ca-certificates openssh-client
RUN wget -q https://storage.googleapis.com/kubernetes-release/release/$(wget -q --output-document -  https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod u+x kubectl && mv kubectl /bin/kubectl
COPY rancher /usr/bin/
WORKDIR /mnt
ENTRYPOINT ["rancher"]
CMD  ["--help"]
```

2022-05-25 08:25 UTC, Trackhe requested changes
@Arno500 you can take this.
```
FROM alpine:3.13
RUN apk add --no-cache ca-certificates openssh-client
RUN wget -q https://storage.googleapis.com/kubernetes-release/release/$(wget -q --output-document -  https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod u+x kubectl && mv kubectl /bin/kubectl
COPY rancher /usr/bin/
WORKDIR /mnt
ENTRYPOINT ["rancher"]
CMD  ["--help"]
```

2022-05-26 16:19 UTC, Trackhe commented
@Arno500 the master branch is not the default branch and dosn`t build. Maybe you can try to pullrequest it to the v2.6 for faster merge.

2022-05-26 16:31 UTC, Arno500 commented
@Trackhe, can you relaunch the checks? Thanks!

2025-05-28 06:32 UTC, Trackhe commented
> @Trackhe @Arno500 sorry for the delay - is this still something you would like to pursue?

Sure it is usefull in some cases, so why not? Is it a big thing to merge this?

2025-05-30 13:42 UTC, closed without merging