add optional path to cache kubectl token
rancher/cli pull request #287
Opened 2020-10-27 11:47 UTC by tjcain

It would be helpful to have an option to specify a path to the cached kubectl token to avoid changing directories requiring a fresh login.

2020-10-28 18:38 UTC, dramich requested changes

2020-10-28 18:38 UTC, dramich commented on cmd/kubectl_token.go
> +				Usage: "The absolute path to place or find a .cache directory containing the kubectl token (also via RANCHER_CACHE_DIR)",
Add the `EnvVar` field here to specify the envvar and the cli will pull from there automatically
```suggestion
				Usage: "The absolute path for the kubectl-token .cache directory"
```

2020-10-28 18:38 UTC, dramich commented on cmd/kubectl_token.go
> +	} else if s := os.Getenv("RANCHER_CACHE_DIR"); s != "" {
Using the `EnvVar` will cover this so it can be dropped

2020-10-28 18:38 UTC, dramich commented on cmd/kubectl_token.go
> +		return "", fmt.Errorf("cache dir require an absolute path")
```suggestion
		return "", fmt.Errorf("cache dir requires an absolute path")
```

2020-10-28 18:38 UTC, dramich commented on cmd/kubectl_token.go
> +	}
Looks like an extra error check

2020-10-28 19:16 UTC, tjcain commented
Thanks for the review, I have made the suggested changes.

2020-10-29 16:48 UTC, dramich approved these changes

2020-10-29 16:48 UTC, merged