Avoid overwriting entire KubeCredentials block
rancher/cli pull request #397
Opened 2024-09-22 14:18 UTC by idogada-akamai

2024-09-26 10:20 UTC, crobby requested changes
Looks like a fine change.
Can you add a small unit test to cover this?

2024-10-07 11:55 UTC, idogada-akamai commented
> Looks like a fine change. Can you add a small unit test to cover this?
@crobby Can you guide me on how to do that?
I found some stuff around the project, but it's not clear to me

2024-10-07 18:17 UTC, crobby commented
> > Looks like a fine change. Can you add a small unit test to cover this?
> > @crobby Can you guide me on how to do that?
> > I found some stuff around the project, but it's not clear to me

The new test would go in kubectl_token_test.go.  We would only need to test the cacheCredential function.
It might be a little bit awkward since I think as it's written right now, you may have to have your test write a config file that would serve as a possible existing configuration so that it can be loaded and rewritten by the function.  The test would then need to check the contents of that file to make sure it contains/doesn't contain the expected entries.

2024-10-08 13:19 UTC, bigkevmcd commented
I've written a test for this fix here https://github.com/rancher/cli/commit/78c6a7c2d699df0b2216b84790485af4557789b8 feel free to copy the test and update the PR, or we can merge it.

2024-10-09 14:17 UTC, idogada-akamai commented
> I've written a test for this fix here [78c6a7c](https://github.com/rancher/cli/commit/78c6a7c2d699df0b2216b84790485af4557789b8) feel free to copy the test and update the PR, or we can merge it.

@bigkevmcd Thank you! I have added the test.

@crobby Can you please review the change and let us know if any further change is required?

2024-10-14 13:56 UTC, crobby commented
> > I've written a test for this fix here [78c6a7c](https://github.com/rancher/cli/commit/78c6a7c2d699df0b2216b84790485af4557789b8) feel free to copy the test and update the PR, or we can merge it.
> 
> @bigkevmcd Thank you! I have added the test.
> 
> @crobby Can you please review the change and let us know if any further change is required?

Will do.
Thank you.

2024-10-29 09:39 UTC, idogada-akamai commented
@crobby 
Fixed the linting error

2024-10-29 09:52 UTC, enrichman commented on cmd/kubectl_token_test.go
> +	cliCtx = cli.NewContext(nil, flagSet, nil)
This context look like the first one. Can we reuse the same?

2024-10-29 11:58 UTC, idogada-akamai commented
@crobby I re-used the existing context for the test

2024-10-29 11:58 UTC, idogada-akamai commented
@enrichman I re-used the context for the test

2024-11-11 10:27 UTC, idogada-akamai commented
@crobby @enrichman 
What's our next steps to getting this pushed?

2024-11-11 15:35 UTC, crobby commented
> @crobby @enrichman What are our next steps to getting this pushed?

Hopefully, we can get reviewed and merged "soon".  I'm not sure which Rancher release will receive this change yet.

2024-11-11 15:35 UTC, crobby approved these changes

2024-11-11 16:56 UTC, enrichman approved these changes

2024-11-11 16:57 UTC, merged

2024-11-14 05:59 UTC, nickvth commented
Releasing this change, would make me happy 😃 So any ideas when?